### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by JSEHV** [Rikujolla/shakkikello#8]
I'd like to suggest an icon that fits well in the Sailfish OS design style, plus reflects the 2 sides of the board (two halfs of the pion) but doesn't intrude too much in the design. 

Colorwise it also pops more, so your app will have a better visual location on peoples phone/tablet screens. Hope you appreciate the effort.

![harbour-shakkikello-172x172](https://user-images.githubusercontent.com/5128988/50169380-c78e3080-02ed-11e9-8105-3644cb9adcf3.png)

Al needed sizes:

[harbour-shakkikello.zip](https://github.com/Rikujolla/shakkikello/files/2691443/harbour-shakkikello.zip)

**Comment by Rikujolla** [comment]
Thank you for your effort. I agree the point you arise. I'll discuss with my piece designer and answer this in near future. He had some new ideas for pieces also so may be we can some how consolidate the ideas

**Comment by Rikujolla** [comment]
I have discussed with my piece designer. The new pieces are still unlike so the icon should also be in line with that idea. The designer is though an old school artist without computer, so there is still space for digitizing ideas (icon, cover page, in app pictures, pieces) and implement and fine tune them to suit to app. If you are interested in that kind of contribution, I'm interested to co-operate. Please inform what are your interests.

**Comment by Rikujolla** [comment]
Thanks for this issue. The new visual components have been made and published.
